galaxy_info:
  author: "Valera1488-s"
  description: "Role for installing and managing Docker"
  company: "YourCompany"  # Можно оставить пустым или указать своё
  license: "MIT"
  min_ansible_version: "2.9"  # ВАЖНО: в кавычках!
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  # Можно добавить другие поля по желанию

dependencies: []
