---
# Плейбук для развертывания Prometheus и Grafana
- name: Deploy Prometheus and Grafana
  hosts: monitoring  # Указываем, что плейбук будет выполняться на хостах из группы "monitoring"
  roles:  # Подключаем роли
    - docker
    - prometheus
    - grafana
    - node_exporter

